<?php

namespace Database\Seeders;

use App\Enums\City\CityStatus;
use App\Enums\Country\CountryStatus;
use App\Models\Area\Area;
use App\Models\City\City;
use App\Models\Country\Country;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        Country::withTrashed()->get()->each->forceDelete();
        City::withTrashed()->get()->each->forceDelete();
        Area::withTrashed()->get()->each->forceDelete();

        $countries = [
            [
                'name' => 'Morocco',
                'iso_code' => 'MA',
                'iso3_code' => 'MAR',
                'status' => CountryStatus::ACTIVE,
                'currency_code' => 'MAD',
                'phone_code' => '+212',
                'cities' => [
                    'Agadir',
                    'Marrakech',
                    'Casablanca',
                    'Rabat',
                    'Tanger',
                    'Ait melloul',
                    'Inezgane',
                    'Tiznit',
                    'Biougra',
                    'Taroudannt',
                    'Belfaa',
                    'Tit Mellil',
                    'Mediouna',
                    'Deroua',
                    'Bouskoura',
                    'Temara',
                    'Sale',
                    'Sala Al Jadida',
                    'Tetouan',
                    'Larache',
                    'Safi',
                    'Dakhla',
                    'Guelmim',
                    "M'diq",
                    'Fnideq',
                    'Chefchaouen',
                    'Aïn Atig',
                    'Sidi Bouknadel',
                    'Tamesna',
                    'Fes',
                    'Mohammadia',
                    'Martil',
                    'Ain Harrouda',
                    'Meknes',
                    'Laayoune',
                    'Kenitra',
                    'EL Jadida',
                    'Sidi Bouzid - El jadida',
                    'Moulay Abdellah Amghar',
                    'Jorf Lasfar',
                    'Temsia',
                    'Oujda',
                    'Oulad Teima',
                    'Lqliâa',
                    'Oulad Dahou',
                    'Sidi Bibi',
                    'Dar bouazza',
                    'Ksar El Kébir',
                    'Mehdia',
                    'Sidi Taibi',
                    'Sidi Yahya El Gharb',
                    'Errachidia',
                    'Arfoud',
                    'Goulmima',
                    'Rissani',
                    'Er-Rich',
                    'Settat',
                    'Berrechid',
                    'Khouribga',
                    'Béni Mellal',
                    'Taza',
                    'Ben Ahmed (Berchid)',
                    'Aourir',
                    'Ait aamira',
                    'Taghazout',
                    'Berkane',
                    'Nador',
                    'Ouarzazate',
                    'Selouane',
                    'Al Aroui',
                    'Segangan',
                    'Beni ensar',
                    'Ain El Aouda',
                    'Kasba Tadla',
                    'Fquih Ben Salah',
                    'El Ksiba',
                    'Souk Sebt Oulad Nemma',
                    'Oulad Ayad',
                    'Afourar',
                    'Oulad moussa',
                    'Bir Jdid',
                    'Lakhyayeta',
                    'had soualem',
                    'Sidi Rehal',
                    'Aït Ourir',
                    'Tahanaout',
                    'Souihla',
                    'Ourika',
                    'BELAAGUID',
                    'Sidi Bou Othmane',
                    'Tamansourt',
                    'Sidi Zouine',
                    'Loudaya',
                    'Oulad Hassoun',
                    'Khénifra',
                    "M'rirt",
                    'Azilal',
                    'Al Hoceïma',
                    'Imzouren',
                    'Azemmour',
                    'Oued Zem',
                    'Sidi Kacem',
                    'Sidi Slimane',
                    'Sebt Gezoula',
                    'Skoura',
                    'Ahfir',
                    'Saïdia',
                    'Bni Drar',
                    'Ras El Ma',
                    'Sidi Bennour',
                    'Khemis Zemamra',
                    'Cafémaure',
                    'Oued Laou',
                    'Ajdir',
                    'Bni Bouayach',
                    'Sidi Smaïl',
                    'Khémisset',
                    'Ouazzane',
                    'Tiflet',
                    'El Hajeb',
                    'Boufakrane',
                    'Sabaa Aiyoun',
                    'Tameslouht',
                    'Nouasser',
                    'Zaouïat Cheikh',
                    'Youssoufia',
                    'Jamâat Shaim',
                    'Zeghanghane',
                    'Targuist',
                    'Assilah',
                    'Ksar Sghir',
                    'Essaouira',
                    'El Mansouria',
                    'Guercif',
                    'Demnate',
                    'Tahla',
                    'Oued Amlil',
                    'Farkhana',
                    'Azrou',
                    'Ifrane',
                    'Moulay Idriss Zerhoun',
                    'Bejaâd',
                    'El Marsa (Laayoune)',
                    'El Kelaâ des Sraghna',
                    'Lâattaouia',
                    'Errahma',
                    'Echemmaia',
                    'Ounagha',
                    'Smimou',
                    'Sebt El Guerdane',
                    'Tin Mansour',
                    'Tamanar',
                    'Talmest',
                    'Midelt',
                    'Tinghir',
                    'Tinejdad',
                    'Aoufous',
                    'Tan-Tan',
                    "Kelaat-M'Gouna",
                    'Boumalne-Dadès',
                    'Ain Taoujdate',
                    'Harhoura',
                    'Bouznika',
                    'Benslimane',
                    'Aklim',
                    'Zaïo',
                    'Bab Taza',
                    'Boumia',
                    'Zaïda',
                    'Bouizakarne',
                    'Skhirate',
                    'Agdz',
                    'Tazenakht',
                    'Séfrou',
                    'Bhalil',
                    'Chichaoua',
                    'Imouzzer Kandar',
                    'Aïn Cheggag',
                    'Ain Beda',
                    'Sidi Khiar Kandar',
                    'Bab Berred',
                    'Ouled Tayeb',
                    'Madagh',
                    'Massa',
                    'Taourirt',
                    'Souk El Arbaa',
                    'Bel Ksiri',
                    'Moulay Bousselham',
                    'Mechra Bel Ksiri',
                    'El Aïoun Sidi Mellouk',
                    'El Aioun Oriental',
                    'Boujniba',
                    'Jaâdar',
                    'Driouch',
                    'Tiztoutine',
                    'Ben Guerir',
                    'Imintanoute',
                    "Sid L'Mokhtar",
                    'Jerada',
                    'Ain Chqef',
                    'Ghazoua',
                    'Oualidia',
                    'Tnine Chtouka - El jadida',
                    'Sidi Jaber',
                    'Bradia',
                    'Taghzirt',
                    'Oulad Frej',
                    'Midar',
                    'Ben Taïeb',
                    'Kariat Arekmane',
                    'Bouarg',
                    'Aïn Dorij',
                    'Zoumi',
                    'Sidi Redouane',
                    'Ait Aissa oubrahim',
                    'Tabesbaste',
                    'Timatraouine',
                    'Imider',
                    'Ait El farsi',
                    'Taounate',
                    'Tissa',
                    'ain aicha',
                    'Missour',
                    'Boulemane',
                    'Merzouga',
                    'Test',
                    'Zagora',
                    'Aguim',
                    'Figuig',
                    'Bouarfa',
                    'Tendrara',
                    'Kassita',
                    'Dar El Kebdani',
                    'Tamsamane',
                    'Boujdour',
                    'Es-Semara',
                    'El Aouamra',
                    'Khémis Sahel',
                    'Ouled Hammou',
                    'Tighassaline',
                    'Aït Ishaq',
                    'Haj Kaddour',
                    'Bni Chiker',
                    'Issaguen',
                    'Boukidan',
                    'El Hanchane',
                    'El Ouatia (Tan-Tan)',
                    'Boudnib',
                    'Outat El Haj',
                    'Aghbalou',
                    'Itzer',
                    'Sidi Ifni',
                    'Tafraout',
                    'Oulad Berhil',
                    'Aoulouz',
                    'Msawar Rasso',
                    'Tamallalt',
                    'Assahrij',
                    'Sidi Allal Tazi',
                    'Assa',
                    'Zag',
                    'Skhour Rehamna',
                    'Aïn Bni Mathar',
                    'Mzoudia',
                    'Mejjat',
                    'Aguelmous',
                    'Elbarj',
                    'Lahri',
                    'Bni Hadifa',
                    'Bouanane',
                    'Aïn Karma',
                    'Sidi sliman Mol kifan',
                    'Boderbala',
                    'Ain Arma',
                    'Agoray',
                    'Dar Oum Sultan',
                    'Tlat Loulad',
                    'Ait Qamra',
                    'Ajdir Igzennayen',
                    'Oulad Ghadbane',
                    'Ouaoumana',
                    'El kebab',
                    'Had Bouhssoussen',
                    'Tighza',
                    'Moulay Bouazza',
                    'Kef en Nsour',
                    'Sebt Ait Rahhou',
                    'Oued Laabid',
                    'Bzou',
                    'El Borouj',
                    'El Menzeh',
                    'Sidi Yahya Zaër',
                    'Agadir messagerie ',
                ],
            ],
            [
                'name' => 'United Arab Emirates',
                'iso_code' => 'AE',
                'iso3_code' => 'ARE',
                'status' => CountryStatus::ACTIVE,
                'currency_code' => 'AED',
                'phone_code' => '+971',
            ],
            [
                'name' => 'Qatar',
                'iso_code' => 'QA',
                'iso3_code' => 'QAT',
                'status' => CountryStatus::ACTIVE,
                'currency_code' => 'QAR',
                'phone_code' => '+974',
            ],
            [
                'name' => 'Kuwait',
                'iso_code' => 'KW',
                'iso3_code' => 'KWT',
                'status' => CountryStatus::ACTIVE,
                'currency_code' => 'KWD',
                'phone_code' => '+965',
            ],
            [
                'name' => 'Bahrain',
                'iso_code' => 'BH',
                'iso3_code' => 'BHR',
                'status' => CountryStatus::ACTIVE,
                'currency_code' => 'BHD',
                'phone_code' => '+973',
                'phone_code' => '+213',

            ],
            // [
            //     'name' => 'United Kingdom',
            //     'iso_code' => 'GB',
            //     'iso3_code' => 'GBR',
            //     'status' => CountryStatus::ACTIVE,
            //     'currency_code' => 'GBP',
            //     'phone_code' => '+44',
            // ],
            // [
            //     'name' => 'Oman',
            //     'iso_code' => 'OM',
            //     'iso3_code' => 'OMN',
            //     'status' => CountryStatus::ACTIVE,
            //     'currency_code' => 'OMR',
            //     'phone_code' => '+968',
            // ],
            // Add more countries as needed
        ];

        foreach ($countries as $cou) {
            $cities = optional($cou)['cities'] ?? [];
            unset($cou['cities']);

            $country = Country::create($cou);

            foreach ($cities as $cityName) {
                City::firstOrCreate([
                    City::NAME_COLUMN_NAME => $cityName,
                    City::COUNTRY_TO_ID_COLUMN_NAME => $country->id,
                    City::STATUS_COLUMN_NAME => CityStatus::ACTIVE,
                ]);
            }

        }
    }
}
